version: "3"

services:
  postgres:
    container_name: "local-ember-postgres"
    restart: on-failure
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres